language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t neerajnsharma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true neerajnsharma/react-test npm run test -- --coverage
  

after_success:
  - docker build -t neerajnsharma/multi-client ./client
  - docker build -t neerajnsharma/multi-nginx ./nginx
  - docker build -t neerajnsharma/multi-server ./server
  - docker build -t neerajnsharma/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push neerajnsharma/multi-client
  - docker push neerajnsharma/multi-nginx
  - docker push neerajnsharma/multi-server
  - docker push neerajnsharma/multi-worker
